<?php

namespace Mondofute\Bundle\FournisseurPrestationAffectationBundle\Repository;

/**
 * FournisseurPrestationAffectationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurPrestationAffectationRepository extends \Doctrine\ORM\EntityRepository
{
}
