<?php

namespace Mondofute\Bundle\FournisseurPrestationAffectationBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;

/**
 * PrestationAnnexeLogementUnifieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestationAnnexeLogementUnifieRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $paramId
     * @param $logementUnifieId
     * @return mixed
     */
    public function findByCriteria($paramId, $logementUnifieId)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('prestationAnnexeLogementUnifie , prestationAnnexeLogements')
            ->from('MondofuteFournisseurPrestationAffectationBundle:PrestationAnnexeLogementUnifie',
                'prestationAnnexeLogementUnifie')
            ->join('prestationAnnexeLogementUnifie.prestationAnnexeLogements', 'prestationAnnexeLogements')
            ->join('prestationAnnexeLogements.logement', 'logement')
            ->join('logement.logementUnifie', 'logementUnifie')
            ->where('prestationAnnexeLogements.param = :paramId')
            ->setParameter('paramId', $paramId)
            ->andWhere('logementUnifie.id = :logementUnifieId')
            ->setParameter('logementUnifieId', $logementUnifieId);

        try {
            $result = $qb->getQuery()->getOneOrNullResult();
        } catch (NonUniqueResultException $exception) {
            dump($paramId);
            dump($logementUnifieId);
            dump($result = $qb->getQuery()->getResult());
            die;
        }
//dump($result);die;
        return $result;
    }

    /**
     * @param $logementUnifieId
     * @return array
     */
    public function findByLogementUnifieId($logementUnifieId)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('prestationAnnexeLogementUnifie ')
            ->from('MondofuteFournisseurPrestationAffectationBundle:PrestationAnnexeLogementUnifie',
                'prestationAnnexeLogementUnifie')
            ->join('prestationAnnexeLogementUnifie.prestationAnnexeLogements', 'prestationAnnexeLogements')
            ->join('prestationAnnexeLogements.logement', 'logement')
            ->join('logement.logementUnifie', 'logementUnifie')
            ->andWhere('logementUnifie.id = :logementUnifieId')
            ->setParameter('logementUnifieId', $logementUnifieId);

        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
