<?php

namespace Mondofute\Bundle\FournisseurPrestationAffectationBundle\Repository;
use Mondofute\Bundle\FournisseurPrestationAnnexeBundle\Entity\FournisseurPrestationAnnexe;

/**
 * PrestationAnnexeHebergementUnifieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestationAnnexeHebergementUnifieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCriteria($fournisseurId, FournisseurPrestationAnnexe $prestationAnnex, $hebergementUnifieId)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('prestationAnnexeHebergementUnifie , prestationAnnexeHebergements')
            ->from('MondofuteFournisseurPrestationAffectationBundle:PrestationAnnexeHebergementUnifie', 'prestationAnnexeHebergementUnifie')
            ->join('prestationAnnexeHebergementUnifie.prestationAnnexeHebergements', 'prestationAnnexeHebergements')
            ->join('prestationAnnexeHebergements.hebergement' , 'hebergement')
            ->join('hebergement.hebergementUnifie' , 'hebergementUnifie')
            ->where('prestationAnnexeHebergements.fournisseurPrestationAnnexe = :prestationAnnex')
            ->setParameter('prestationAnnex' , $prestationAnnex->getId())
            ->andWhere('prestationAnnexeHebergements.fournisseur = :fournisseurId')
            ->setParameter('fournisseurId' ,$fournisseurId )
            ->andWhere('hebergementUnifie.id = :hebergementUnifieId')
            ->setParameter('hebergementUnifieId' ,$hebergementUnifieId )
        ;

        $result = $qb->getQuery()->getOneOrNullResult();
//        $result = $qb->getQuery()->getFirstResult();
//        dump($result);die;
        return $result;
    }

    public function findByHebergement($hebergementId)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('prestationAnnexeHebergementUnifie')
            ->from('MondofuteFournisseurPrestationAffectationBundle:PrestationAnnexeHebergementUnifie', 'prestationAnnexeHebergementUnifie')
            ->join('prestationAnnexeHebergementUnifie.prestationAnnexeHebergements' , 'prestationAnnexeHebergements')
            ->join('prestationAnnexeHebergements.hebergement' , 'hebergement')
            ->where('hebergement.id = :hebergementId')
            ->setParameter('hebergementId' , $hebergementId)
        ;
        $result = $qb->getQuery()->getResult();
//        dump($result);die;
        return $result;
    }

    public function findByHebergementUnifie($hebergementUnifieId)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('prestationAnnexeHebergementUnifie')
            ->from('MondofuteFournisseurPrestationAffectationBundle:PrestationAnnexeHebergementUnifie', 'prestationAnnexeHebergementUnifie')
            ->join('prestationAnnexeHebergementUnifie.prestationAnnexeHebergements' , 'prestationAnnexeHebergements')
            ->join('prestationAnnexeHebergements.hebergement' , 'hebergement')
            ->join('hebergement.hebergementUnifie' , 'hebergementUnifie')
            ->where('hebergementUnifie.id = :hebergementUnifieId')
            ->setParameter('hebergementUnifieId' , $hebergementUnifieId)
        ;
        $result = $qb->getQuery()->getResult();
//        dump($result);die;
        return $result;
    }
}
