<?php

namespace Mondofute\Bundle\FournisseurPrestationAffectationBundle\Repository;

/**
 * PrestationAnnexeHebergementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestationAnnexeHebergementRepository extends \Doctrine\ORM\EntityRepository
{
}
