<?php

namespace Mondofute\Bundle\FournisseurPrestationAffectationBundle\Repository;

use Mondofute\Bundle\FournisseurPrestationAnnexeBundle\Entity\FournisseurPrestationAnnexe;
use Mondofute\Bundle\StationBundle\Entity\StationUnifie;

/**
 * PrestationAnnexeStationUnifieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestationAnnexeStationUnifieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCriteria(FournisseurPrestationAnnexe $prestationAnnex, $stationUnifieId)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('prestationAnnexeStationUnifie , prestationAnnexeStations')
            ->from('MondofuteFournisseurPrestationAffectationBundle:PrestationAnnexeStationUnifie', 'prestationAnnexeStationUnifie')
            ->join('prestationAnnexeStationUnifie.prestationAnnexeStations', 'prestationAnnexeStations')
            ->join('prestationAnnexeStations.station', 'station')
            ->join('station.stationUnifie', 'stationUnifie')
            ->where('prestationAnnexeStations.fournisseurPrestationAnnexe = :prestationAnnex')
            ->setParameter('prestationAnnex', $prestationAnnex->getId())
            ->andWhere('stationUnifie.id = :stationUnifieId')
            ->setParameter('stationUnifieId', $stationUnifieId);

        $result = $qb->getQuery()->getOneOrNullResult();
//        $result = $qb->getQuery()->getFirstResult();
//        dump($result);die;
        return $result;
    }

    public function findByStationUnifie(StationUnifie $stationUnifie)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('prestationAnnexeStationUnifie')
            ->from('MondofuteFournisseurPrestationAffectationBundle:PrestationAnnexeStationUnifie', 'prestationAnnexeStationUnifie')
            ->join('prestationAnnexeStationUnifie.prestationAnnexeStations', 'prestationAnnexeStations')
            ->join('prestationAnnexeStations.station', 'station')
            ->join('station.stationUnifie', 'stationUnifie')
            ->andWhere('stationUnifie.id = :stationUnifieId')
            ->setParameter('stationUnifieId', $stationUnifie->getId());

        $result = $qb->getQuery()->getResult();
//        $result = $qb->getQuery()->getFirstResult();
//        dump($result);die;
        return $result;
    }
}
