<?php

namespace Mondofute\Bundle\FournisseurPrestationAffectationBundle\Repository;

/**
 * PrestationAnnexeLogementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestationAnnexeLogementRepository extends \Doctrine\ORM\EntityRepository
{
}
