<?php

namespace Mondofute\Bundle\LangueBundle\Repository;

/**
 * LangueTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LangueTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
