<?php

namespace Mondofute\Bundle\ServiceBundle\Repository;

/**
 * CategorieServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
