CREATE TABLE sous_type_prestation_annexe (id INT UNSIGNED AUTO_INCREMENT NOT NULL, type_prestation_annexe_id INT UNSIGNED DEFAULT NULL, INDEX IDX_3A06D82675427125 (type_prestation_annexe_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE sous_type_prestation_annexe_traduction (id INT UNSIGNED AUTO_INCREMENT NOT NULL, sous_type_prestation_annexe_id INT UNSIGNED DEFAULT NULL, langue_id INT UNSIGNED DEFAULT NULL, libelle VARCHAR(255) NOT NULL, INDEX IDX_E93F4FC6FA03157A (sous_type_prestation_annexe_id), INDEX IDX_E93F4FC62AADBACD (langue_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE type_prestation_annexe (id INT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE type_prestation_annexe_traduction (id INT UNSIGNED AUTO_INCREMENT NOT NULL, type_prestation_annexe_id INT UNSIGNED DEFAULT NULL, langue_id INT UNSIGNED DEFAULT NULL, libelle VARCHAR(255) NOT NULL, INDEX IDX_ED7238D075427125 (type_prestation_annexe_id), INDEX IDX_ED7238D02AADBACD (langue_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE sous_type_prestation_annexe ADD CONSTRAINT FK_3A06D82675427125 FOREIGN KEY (type_prestation_annexe_id) REFERENCES type_prestation_annexe (id);
ALTER TABLE sous_type_prestation_annexe_traduction ADD CONSTRAINT FK_E93F4FC6FA03157A FOREIGN KEY (sous_type_prestation_annexe_id) REFERENCES sous_type_prestation_annexe (id);
ALTER TABLE sous_type_prestation_annexe_traduction ADD CONSTRAINT FK_E93F4FC62AADBACD FOREIGN KEY (langue_id) REFERENCES langue (id);
ALTER TABLE type_prestation_annexe_traduction ADD CONSTRAINT FK_ED7238D075427125 FOREIGN KEY (type_prestation_annexe_id) REFERENCES type_prestation_annexe (id);
ALTER TABLE type_prestation_annexe_traduction ADD CONSTRAINT FK_ED7238D02AADBACD FOREIGN KEY (langue_id) REFERENCES langue (id);
