<?php

namespace Mondofute\Bundle\CatalogueBundle\Repository;

use Doctrine\ORM\EntityManager;

/**
 * LogementPeriodeLocatifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogementPeriodeLocatifRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteByLogement($logementId)
    {
        $sql = 'DELETE FROM logement_periode_locatif WHERE logement_id = :logementId';
        $params = array(
            'logementId' => $logementId,
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params);
    }

    public function findByPrixPublicNotEmpty($fournisseurId, $hebergementId)
    {

        /** @var EntityManager $em */
        $em = $this->getEntityManager();
        $connection = $em->getConnection();

        $sql = 'select p.id periodeId, p.debut, p.fin, l.id logementId from logement_periode_locatif lpl
                left join periode p on p.id = lpl.periode_id
                left join logement l on l.id = lpl.logement_id
                left join fournisseur_hebergement fh on fh.id = l.fournisseur_hebergement_id 
                left join hebergement h on h.hebergement_unifie_id = fh.hebergement_id  
                where lpl.prix_public > 0 
                and fh.fournisseur_id = ' . $fournisseurId . ' 
                and h.id = ' . $hebergementId . ' 
                and l.site_id = h.site_id
                group by periode_id';

        $logementPeriodeLocatifs = $connection->executeQuery($sql)->fetchAll();

        return $logementPeriodeLocatifs;

    }
}
