<?php

namespace Mondofute\Bundle\CatalogueBundle\Repository;

use Doctrine\ORM\EntityManager;

/**
 * LogementPeriodeLocatifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogementPeriodeLocatifRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteByLogement($logementId)
    {
        $sql = 'DELETE FROM logement_periode_locatif WHERE logement_id = :logementId';
        $params = array(
            'logementId' => $logementId,
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params);
    }

    public function findByPrixPublicNotEmpty()
    {
        /** @var EntityManager $em */
        $em = $this->getEntityManager();
        $connection = $em->getConnection();

        $sql = 'select p.id periodeId, p.type_id typeId,  p.debut, p.fin from logement_periode_locatif lpl
                left join periode p on p.id = lpl.periode_id
                where lpl.prix_public > 0
                group by periode_id';

        $logementPeriodeLocatifs = $connection->executeQuery($sql)->fetchAll();

        return $logementPeriodeLocatifs;

    }
}
