<?php

namespace Mondofute\Bundle\LogementPeriodeBundle\Repository;

/**
 * LogementPeriodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogementPeriodeRepository extends \Doctrine\ORM\EntityRepository
{
}
