<?php

namespace Mondofute\Bundle\CodePromoBundle\Repository;

/**
 * CodePromoClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodePromoClientRepository extends \Doctrine\ORM\EntityRepository
{
}
