<?php

namespace Mondofute\Bundle\CodePromoBundle\Repository;

/**
 * CodePromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodePromoRepository extends \Doctrine\ORM\EntityRepository
{
}
