<?php

namespace Mondofute\Bundle\CodePromoBundle\Repository;

/**
 * CodePromoUnifieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodePromoUnifieRepository extends \Doctrine\ORM\EntityRepository
{
}
