<?php

namespace Mondofute\Bundle\PeriodeBundle\Repository;

use Doctrine\Common\Collections\Criteria;

/**
 * PeriodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $debut
     * @param $fin
     * @param null $type
     * @param null $nbJour
     * @return \Doctrine\Common\Collections\Collection
     */
    public function rechercherPeriodesIntervale($debut, $fin, $type = null, $nbJour = null)
    {
        $criteres = new Criteria();
        $criteres->where($criteres->expr()->gte('debut', $debut));
        $criteres->andWhere($criteres->expr()->lte('fin', $fin));
        if (!empty($type)) {
            $criteres->andWhere($criteres->expr()->eq('type', $type));
        }
        if (!empty($nbJour)) {
            $criteres->andWhere($criteres->expr()->eq('nbJour', $nbJour));
        }
        return $this->matching($criteres);
    }
}
