CREATE TABLE anite (id INT NOT NULL, param1 VARCHAR(255) NOT NULL, param2 VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE arkiane (id INT NOT NULL, url VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE homeresa (id INT NOT NULL, param_d VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE pass (id INT AUTO_INCREMENT NOT NULL, libelle VARCHAR(255) NOT NULL, classe VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE param_passerelle (id INT AUTO_INCREMENT NOT NULL, passerelle_id INT DEFAULT NULL, discr INT NOT NULL, INDEX IDX_6D47B385EBCA6F32 (passerelle_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE pierre_vacances (id INT NOT NULL, url VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE softbook (id INT NOT NULL, type_id INT DEFAULT NULL, param_a VARCHAR(255) NOT NULL, param_b VARCHAR(255) NOT NULL, INDEX IDX_25DA373C54C8C93 (type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE softbook_type (id INT AUTO_INCREMENT NOT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE anite ADD CONSTRAINT FK_8804F05ABF396750 FOREIGN KEY (id) REFERENCES param_passerelle (id) ON DELETE CASCADE;
ALTER TABLE arkiane ADD CONSTRAINT FK_D138B8D9BF396750 FOREIGN KEY (id) REFERENCES param_passerelle (id) ON DELETE CASCADE;
ALTER TABLE homeresa ADD CONSTRAINT FK_4FE7A6F5BF396750 FOREIGN KEY (id) REFERENCES param_passerelle (id) ON DELETE CASCADE;
ALTER TABLE param_passerelle ADD CONSTRAINT FK_6D47B385EBCA6F32 FOREIGN KEY (passerelle_id) REFERENCES pass (id);
ALTER TABLE pierre_vacances ADD CONSTRAINT FK_39E0C3C7BF396750 FOREIGN KEY (id) REFERENCES param_passerelle (id) ON DELETE CASCADE;
ALTER TABLE softbook ADD CONSTRAINT FK_25DA373C54C8C93 FOREIGN KEY (type_id) REFERENCES softbook_type (id);
ALTER TABLE softbook ADD CONSTRAINT FK_25DA373BF396750 FOREIGN KEY (id) REFERENCES param_passerelle (id) ON DELETE CASCADE;

ALTER TABLE `fournisseur`
	DROP FOREIGN KEY `FK_369ECA32EBCA6F32`;
DROP INDEX IDX_369ECA32EBCA6F32 ON fournisseur;
ALTER TABLE fournisseur ADD param_passerelle_id INT DEFAULT NULL, DROP passerelle_id;
ALTER TABLE fournisseur ADD CONSTRAINT FK_369ECA32A6EF357E FOREIGN KEY (param_passerelle_id) REFERENCES param_passerelle (id);
CREATE UNIQUE INDEX UNIQ_369ECA32A6EF357E ON fournisseur (param_passerelle_id);