<?php

namespace Mondofute\Bundle\SiteBundle\Repository;

use Mondofute\Bundle\SiteBundle\Entity\Site;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends \Doctrine\ORM\EntityRepository
{
    public function chargerSansCrmParClassementAffichage()
    {
        $em = $this->getEntityManager();
        $sites = $em->getRepository(Site::class)->findBy(array('crm' => 0),
            array('classementAffichage' => 'ASC'));
        return $sites;
    }

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getSitesSansCrm()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('site')
            ->where('site.crm != 1')
            ->from('MondofuteSiteBundle:Site', 'site');
        $qb->orderBy('site.classementAffichage', 'ASC');

        return $qb;
    }
}
