<?php

namespace Mondofute\Bundle\PrestationAnnexeBundle\Repository;

/**
 * FamillePrestationAnnexeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamillePrestationAnnexeRepository extends \Doctrine\ORM\EntityRepository
{
}
