<?php

namespace Mondofute\Bundle\PrestationAnnexeBundle\Repository;

/**
 * PrestationAnnexeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestationAnnexeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $locale
     * @return \Doctrine\ORM\QueryBuilder
     */
    // récupérer les traduction des stations crm qui sont de la langue locale
    public function getTraductionsByLocale($locale)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('s , st')
            ->from('MondofutePrestationAnnexeBundle:PrestationAnnexe', 's')
            ->join('s.traductions', 'st')
            ->join('s.site', 'site')
            ->join('st.langue', 'l')
            ->where("l.code = '$locale'")
            ->andWhere('site.crm = 1')
        ;
//        ->setParameter('code' , $locale)
        $qb->orderBy('s.id', 'ASC');

        return $qb;
    }
}
