<?php

namespace Mondofute\Bundle\HebergementBundle\Form;

use Mondofute\Bundle\FournisseurBundle\Entity\Fournisseur;
use Mondofute\Bundle\RemiseClefBundle\Entity\RemiseClef;
use Nucleus\MoyenComBundle\Entity\Adresse;
use Nucleus\MoyenComBundle\Entity\TelFixe;
use Nucleus\MoyenComBundle\Entity\TelMobile;
use Nucleus\MoyenComBundle\Form\AdresseType;
use Nucleus\MoyenComBundle\Form\TelFixeType;
use Nucleus\MoyenComBundle\Form\TelMobileType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\ChoiceList\View\ChoiceView;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FournisseurHebergementType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('fournisseur', EntityType::class, array(
                'class' => Fournisseur::class,
                'choice_label' => 'enseigne',
                'attr' => array('style' => 'display:none'),
                'label_attr' => array('style' => 'display: none')
            ))
            ->add('telFixe', TelFixeType::class, array('data_class' => TelFixe::class))
            ->add('telMobile', TelMobileType::class, array('data_class' => TelMobile::class))
            ->add('adresse', AdresseType::class, array('data_class' => Adresse::class))
            ->add('traductions', CollectionType::class, array(
                'entry_type' => FournisseurHebergementTraductionType::class,
                'allow_add' => true,
                'prototype_name' => '__tradname__',
                'label_attr' => array('style' => 'display:none')
            ))
            ->add('remiseClef', EntityType::class, array(
                'class' => RemiseClef::class,
                'placeholder' => 'Veuillez choisir un profil de remise de clef',
                'choice_label' => 'libelle',
            ));
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Mondofute\Bundle\HebergementBundle\Entity\FournisseurHebergement'
        ));
    }

    public function finishView(FormView $view, FormInterface $form, array $options)
    {

//        parent::finishView($view, $form, $options); // TODO: Change the autogenerated stub
//        Ajoute l'attr data-fournisseur aux options du select
        foreach ($view->children['remiseClef']->vars['choices'] as $choice) {
            $choice->attr['data-fournisseur'] = $choice->data->getFournisseur()->getId();
        }
//        ajoute l'option 'nouveau' dans le select remise de clef
        $option = new ChoiceView(array(), 'add', 'nouveau');
        $view->children['remiseClef']->vars['choices'][] = $option;

    }
}
