/*CREATE TABLE promotion_traduction (id INT UNSIGNED AUTO_INCREMENT NOT NULL, promotion_id INT UNSIGNED DEFAULT NULL, langue_id INT UNSIGNED DEFAULT NULL, titre VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, INDEX IDX_8A22280C139DF194 (promotion_id), INDEX IDX_8A22280C2AADBACD (langue_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE promotion_traduction ADD CONSTRAINT FK_8A22280C139DF194 FOREIGN KEY (promotion_id) REFERENCES promotion (id);
ALTER TABLE promotion_traduction ADD CONSTRAINT FK_8A22280C2AADBACD FOREIGN KEY (langue_id) REFERENCES langue (id);*/

CREATE TABLE promotion_logement (promotion_id INT UNSIGNED NOT NULL, logement_id INT UNSIGNED NOT NULL, INDEX IDX_36A9E013139DF194 (promotion_id), INDEX IDX_36A9E01358ABF955 (logement_id), PRIMARY KEY(promotion_id, logement_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE promotion_logement ADD CONSTRAINT FK_36A9E013139DF194 FOREIGN KEY (promotion_id) REFERENCES promotion (id);
ALTER TABLE promotion_logement ADD CONSTRAINT FK_36A9E01358ABF955 FOREIGN KEY (logement_id) REFERENCES logement (id);