<?php

namespace HiDev\Bundle\AuteurBundle\Repository;

/**
 * UtilisateurAuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurAuteurRepository extends \Doctrine\ORM\EntityRepository
{
}
