<?php

namespace Mondofute\Bundle\FournisseurPrestationAnnexeBundle\Repository;

/**
 * FournisseurPrestationAnnexeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurPrestationAnnexeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $locale
     * @return \Doctrine\ORM\QueryBuilder
     */
    // récupérer les traduction des stations crm qui sont de la langue locale
    public function getTraductionsByLocale($locale, $famillePrestationAnnexeId)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('s , st')
            ->from('MondofuteFournisseurPrestationAnnexeBundle:FournisseurPrestationAnnexe', 's')
            ->join('s.traductions', 'st')
            ->join('st.langue', 'l')
            ->where("l.code = '$locale'")
        ;
//        if(!empty($famillePrestationAnnexeId)){
//            $qb
//                ->andWhere('s.famillePrestationAnnexe = :famillePrestationAnnexeId ')
//                ->setParameter('famillePrestationAnnexeId' , $famillePrestationAnnexeId)
//            ;
//        }

//        ->setParameter('code' , $locale)
        $qb->orderBy('s.id', 'ASC');

        return $qb;
    }
}
