<?php

namespace Mondofute\Bundle\FournisseurPrestationAnnexeBundle\Repository;

/**
 * FournisseurPrestationAnnexeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurPrestationAnnexeRepository extends \Doctrine\ORM\EntityRepository
{
}
