<?php

namespace Mondofute\Bundle\FournisseurPrestationAnnexeBundle\Repository;

/**
 * PeriodeValiditeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodeValiditeRepository extends \Doctrine\ORM\EntityRepository
{
}
