<?php

namespace Mondofute\Bundle\GeographieBundle\Repository;

/**
 * CoordonneesGpsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordonneesGpsRepository extends \Doctrine\ORM\EntityRepository
{
}
