<?php

namespace Mondofute\Bundle\GeographieBundle\Repository;

/**
 * DepartementTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
