<?php

namespace Mondofute\Bundle\GeographieBundle\Repository;

/**
 * DomaineTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomaineTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
