<?php

namespace Mondofute\Bundle\GeographieBundle\Repository;

/**
 * DomaineCarteIdentiteTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomaineCarteIdentiteTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
