<?php

namespace Mondofute\Bundle\GeographieBundle\Repository;

/**
 * GrandeVilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrandeVilleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $locale
     * @return \Doctrine\ORM\QueryBuilder
     */
    // récupérer les traductioin des départements crm qui sont de la langue locale
    public function getTraductionsByLocale($locale)
    {

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('grandeVille , traductions')
            ->from('MondofuteGeographieBundle:GrandeVille', 'grandeVille')
            ->join('grandeVille.traductions', 'traductions')
            ->join('traductions.langue', 'langue')
            ->where("langue.code = '$locale'");
//        ->setParameter('code' , $locale)
        $qb->orderBy('grandeVille.id', 'ASC');

        return $qb;
    }
}
