<?php

namespace Mondofute\Bundle\GeographieBundle\Repository;

/**
 * RegionImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionImageRepository extends \Doctrine\ORM\EntityRepository
{
}
