<?php

namespace Mondofute\Bundle\GeographieBundle\Repository;

/**
 * RegionImageTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionImageTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
