<?php

namespace Mondofute\Bundle\GeographieBundle\Repository;

/**
 * SecteurImageTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecteurImageTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
