<?php

namespace Mondofute\Bundle\GeographieBundle\Repository;

/**
 * SecteurImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecteurImageRepository extends \Doctrine\ORM\EntityRepository
{
}
