<?php

namespace Mondofute\Bundle\GeographieBundle\Repository;

/**
 * ZoneTouristiquePhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneTouristiquePhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
