<?php

namespace Mondofute\Bundle\GeographieBundle\Repository;

/**
 * ZoneTouristiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneTouristiqueRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $locale
     * @return \Doctrine\ORM\QueryBuilder
     */
    // récupérer les traductioin des zone touristiques crm qui sont de la langue locale
    public function getTraductionsZoneTouristiquesByLocale($locale)
    {

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('zoneTouristique , traductions')
            ->from('MondofuteGeographieBundle:ZoneTouristique', 'zoneTouristique')
            ->join('zoneTouristique.traductions', 'traductions')
            ->join('zoneTouristique.site', 'site')
            ->join('traductions.langue', 'langue')
            ->where("langue.code = '$locale'");
//        ->setParameter('code' , $locale)
        $qb->orderBy('zoneTouristique.zoneTouristiqueUnifie', 'ASC');

        return $qb;
    }
}
