CREATE TABLE code_promo_fournisseur (id INT UNSIGNED AUTO_INCREMENT NOT NULL, fournisseur_id INT UNSIGNED DEFAULT NULL, code_promo_id INT UNSIGNED DEFAULT NULL, INDEX IDX_81945EBC670C757F (fournisseur_id), INDEX IDX_81945EBC294102D4 (code_promo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE code_promo_fournisseur ADD CONSTRAINT FK_81945EBC670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id);
ALTER TABLE code_promo_fournisseur ADD CONSTRAINT FK_81945EBC294102D4 FOREIGN KEY (code_promo_id) REFERENCES code_promo (id);
