
ALTER TABLE logement_periode_locatif DROP FOREIGN KEY FK_505E2A4A58ABF955;
ALTER TABLE logement_periode_locatif DROP FOREIGN KEY FK_505E2A4AF384C1CF;
ALTER TABLE logement_periode_locatif ADD CONSTRAINT FK_505E2A4A58ABF955 FOREIGN KEY (logement_id) REFERENCES logement (id);
ALTER TABLE logement_periode_locatif ADD CONSTRAINT FK_505E2A4AF384C1CF FOREIGN KEY (periode_id) REFERENCES periode (id);