<?php

namespace Mondofute\Bundle\LogementBundle\Form;

use Mondofute\Bundle\SaisonBundle\Form\SaisonCodePasserelleType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LogementUnifieType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('logements', CollectionType::class,
                array('entry_type' => LogementType::class, 'entry_options' => array('locale' => $options["locale"])))
            ->add('desactive')
            ->add('saisonCodePasserelles', CollectionType::class,
                [
                    'entry_type' => SaisonCodePasserelleType::class,
                ]);
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Mondofute\Bundle\LogementBundle\Entity\LogementUnifie',
            'locale' => 'fr_FR'
        ));
    }

    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        parent::finishView($view, $form, $options); // TODO: Change the autogenerated stub
        foreach ($view->children['logements'] as $logement) {
            if ($logement->vars['value']->getSite()->getCrm() == 1) {
                $logementCrm = $logement;
            } else {
                foreach ($logement->children['photos'] as $key => $photo) {
                    if ($photo->vars['value']->getActif() == true) {

                        $siteId = $logement->vars['value']->getSite()->getId();
                        $logementCrm->children['photos']->children[$key]->children['sites']->children[$siteId]->vars['attr'] = array('checked' => 'checked');
                    }
                }
            }

        }
    }
}
