<?php

namespace Mondofute\Bundle\TrancheHoraireBundle\Repository;

/**
 * TrancheHoraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrancheHoraireRepository extends \Doctrine\ORM\EntityRepository
{
}
