<?php

namespace Mondofute\Bundle\CommentaireBundle\Repository;

/**
 * CommentaireUtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireUtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
