<?php

namespace Mondofute\Bundle\CommentaireBundle\Repository;

/**
 * CommentaireClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireClientRepository extends \Doctrine\ORM\EntityRepository
{
}
