<?php

namespace HiDev\Bundle\CodePromoBundle\Repository;

/**
 * CodePromoPeriodeValidateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodePromoPeriodeValidateRepository extends \Doctrine\ORM\EntityRepository
{
}
