<?php

namespace Mondofute\Bundle\SaisonBundle\Repository;

/**
 * SaisonHebergementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisonHebergementRepository extends \Doctrine\ORM\EntityRepository
{
}
