<?php

namespace Mondofute\Bundle\SaisonBundle\Repository;

/**
 * SaisonFournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisonFournisseurRepository extends \Doctrine\ORM\EntityRepository
{
}
