<?php

namespace Mondofute\Bundle\SaisonBundle\Repository;

/**
 * SaisonCodePasserelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisonCodePasserelleRepository extends \Doctrine\ORM\EntityRepository
{
}
