<?php

namespace Mondofute\Bundle\UniteBundle\Repository;

/**
 * ClassementHebergementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassementHebergementRepository extends \Doctrine\ORM\EntityRepository
{
}
