<?php

namespace Mondofute\Bundle\UniteBundle\Repository;

/**
 * DistanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistanceRepository extends \Doctrine\ORM\EntityRepository
{
}
