<?php

namespace Mondofute\Bundle\UniteBundle\Repository;

/**
 * UnitePeriodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitePeriodeRepository extends \Doctrine\ORM\EntityRepository
{
}
