<?php

namespace Mondofute\Bundle\UniteBundle\Repository;

/**
 * UniteTarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniteTarifRepository extends \Doctrine\ORM\EntityRepository
{
}
