<?php

namespace Mondofute\Bundle\UniteBundle\Repository;

/**
 * UniteAgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniteAgeRepository extends \Doctrine\ORM\EntityRepository
{
}
