<?php

namespace Mondofute\Bundle\FournisseurBundle\Repository;

/**
 * FournisseurInterlocuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurInterlocuteurRepository extends \Doctrine\ORM\EntityRepository
{
}
