<?php

namespace Mondofute\Bundle\FournisseurBundle\Repository;

/**
 * InterlocuteurFonctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterlocuteurFonctionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $locale
     * @return \Doctrine\ORM\QueryBuilder
     */
    // récupérer les traductioins qui sont de la langue locale
    public function getTraductionsByLocale($locale)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('interlocuteurFonction , traductions ')
            ->from('MondofuteFournisseurBundle:InterlocuteurFonction', 'interlocuteurFonction')
            ->join('interlocuteurFonction.traductions', 'traductions')
            ->join('traductions.langue', 'langue')
            ->where("langue.code = :code")
            ->setParameter('code', $locale)
            ->orderBy('interlocuteurFonction.id', 'ASC');

        return $qb;
    }
}
