<?php

namespace Mondofute\Bundle\FournisseurBundle\Repository;

/**
 * TypeFournisseurTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeFournisseurTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
