<?php

namespace Mondofute\Bundle\FournisseurBundle\Repository;

/**
 * TypeFournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeFournisseurRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $locale
     * @return \Doctrine\ORM\QueryBuilder
     */
    // récupérer les traductioin des départements crm qui sont de la langue locale
    public function getTraductionsByLocale($locale)
    {

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('typeFournisseur, traductions')
            ->from('MondofuteFournisseurBundle:TypeFournisseur', 'typeFournisseur')
            ->join('typeFournisseur.traductions', 'traductions')
            ->join('traductions.langue', 'langue')
            ->where("langue.code = '$locale'");
//        ->setParameter('code' , $locale)
        $qb->orderBy('typeFournisseur.id', 'ASC');

        return $qb;
    }
}
