<?php

namespace Mondofute\Bundle\PasserelleBundle\Repository;

/**
 * CodePasserelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodePasserelleRepository extends \Doctrine\ORM\EntityRepository
{
}
