<?php

namespace Mondofute\Bundle\PasserelleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HomeresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeresaRepository extends EntityRepository
{
}
