<?php

namespace HiDev\PasserelleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SoftbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftbookRepository extends EntityRepository
{
}
