<?php

namespace Mondofute\Bundle\LogementBundle\Repository;

/**
 * LogementPhotoTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogementPhotoTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
