<?php

namespace Mondofute\Bundle\LogementBundle\Repository;

/**
 * LogementPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogementPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
