<?php

namespace Mondofute\Bundle\LogementBundle\Repository;

/**
 * LogemenPhotoTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogemenPhotoTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
