<?php

namespace Mondofute\Bundle\LogementBundle\Repository;

/**
 * NombreDeChambreTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NombreDeChambreTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
