<?php

namespace Mondofute\Bundle\RemiseClefBundle\Repository;

/**
 * RemiseClefTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemiseClefTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
