<?php

namespace Mondofute\Bundle\RemiseClefBundle\Repository;

/**
 * RemiseClefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemiseClefRepository extends \Doctrine\ORM\EntityRepository
{
}
