<?php

namespace Mondofute\Bundle\StationBundle\Repository;

/**
 * LabelStationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelStationRepository extends \Doctrine\ORM\EntityRepository
{
}
