<?php

namespace Mondofute\Bundle\StationBundle\Repository;

/**
 * StationTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StationTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
