<?php

namespace Mondofute\Bundle\StationBundle\Repository;

/**
 * StationCommentVenirGrandeVilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StationCommentVenirGrandeVilleRepository extends \Doctrine\ORM\EntityRepository
{
}
