<?php

namespace Mondofute\Bundle\StationBundle\Repository;

/**
 * StationCommentVenirTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StationCommentVenirTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
