<?php

namespace Mondofute\Bundle\StationBundle\Repository;

/**
 * StationCarteIdentiteUnifieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StationCarteIdentiteUnifieRepository extends \Doctrine\ORM\EntityRepository
{
}
