<?php

namespace Mondofute\Bundle\StationBundle\Repository;

/**
 * StationDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StationDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
