<?php

namespace Mondofute\Bundle\DecoteBundle\Repository;

/**
 * DecoteLogementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecoteLogementRepository extends \Doctrine\ORM\EntityRepository
{
}
