<?php

namespace Mondofute\Bundle\DecoteBundle\Repository;

/**
 * DecoteStationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecoteStationRepository extends \Doctrine\ORM\EntityRepository
{
}
