<?php

namespace Mondofute\Bundle\DecoteBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
use Mondofute\Bundle\DecoteBundle\Entity\DecoteUnifie;

/**
 * DecoteUnifieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecoteUnifieRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     */
    public function countTotal()
    {
        return $this->createQueryBuilder('entity')
            ->select('COUNT(entity)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * Get the paginated list of published secteurs
     *
     * @param int $page
     * @param int $maxperpage
     * @param $locale
     * @param array $sortbyArray
     * @param int $site
     * @return Paginator
     */
    public function getList($page = 1, $maxperpage, $locale, $sortbyArray = array(), $site = 1)
    {
        $q = $this->createQueryBuilder('unifie')
            ->select('unifie')
            ->join('unifie.decotes', 'entities')
            ->where('entities.site = :site')
            ->setParameter('site', $site)
            ->setFirstResult(($page - 1) * $maxperpage)
            ->setMaxResults($maxperpage);

        foreach ($sortbyArray as $key => $item) {
            $q
                ->orderBy($key, $item);
        }

        return new Paginator($q);
    }

    /**
     * @param DecoteUnifie $decoteUnifie
     * @return mixed
     */
    public function getDecoteUnifieByCode($decoteUnifie)
    {
        $qb = $this->createQueryBuilder('entity')
            ->select('COUNT(entity)')
            ->where('entity.code = :code')
            ->setParameter('code', $decoteUnifie->getCode());

        if (!empty($decoteUnifie->getId())) {
            $qb
                ->andWhere('entity.id != :decoteUnifieId')
                ->setParameter('decoteUnifieId', $decoteUnifie->getId());
        }

//        $qb
//            ->getQuery()
//            ->getSingleScalarResult()
//        ;

        return $qb->getQuery()->getSingleScalarResult();
    }


}
