<?php

namespace Mondofute\Bundle\DecoteBundle\Repository;

/**
 * DecotePeriodeValiditeJourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecotePeriodeValiditeJourRepository extends \Doctrine\ORM\EntityRepository
{
}
