<?php

namespace Mondofute\Bundle\GeographieBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProfilUnifieType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('profils', CollectionType::class, array('entry_type' => ProfilType::class));
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Mondofute\Bundle\GeographieBundle\Entity\ProfilUnifie'
        ));
    }

    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        parent::finishView($view, $form, $options); // TODO: Change the autogenerated stub
        foreach ($view->children['profils'] as $profil) {
            if ($profil->vars['value']->getSite()->getCrm() == 1) {
                $profilCrm = $profil;
            } else {
                foreach ($profil->children['images'] as $key => $image) {
                    if ($image->vars['value']->getActif() == true) {

                        $siteId = $profil->vars['value']->getSite()->getId();
//                    $profilCrm->children['images']->children[$key]
                        $profilCrm->children['images']->children[$key]->children['sites']->children[$siteId]->vars['attr'] = array('checked' => 'checked');
                    }
                }
                foreach ($profil->children['photos'] as $key => $photo) {
                    if ($photo->vars['value']->getActif() == true) {

                        $siteId = $profil->vars['value']->getSite()->getId();
                        $profilCrm->children['photos']->children[$key]->children['sites']->children[$siteId]->vars['attr'] = array('checked' => 'checked');
                    }
                }
                foreach ($profil->children['videos'] as $key => $video) {
                    if ($video->vars['value']->getActif() == true) {

                        $siteId = $profil->vars['value']->getSite()->getId();
                        $profilCrm->children['videos']->children[$key]->children['sites']->children[$siteId]->vars['attr'] = array('checked' => 'checked');
                    }
                }
            }

        }
    }
}
