<?php

namespace Mondofute\Bundle\GeographieBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ZoneTouristiqueUnifieType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('zoneTouristiques', CollectionType::class, array('entry_type' => ZoneTouristiqueType::class));
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Mondofute\Bundle\GeographieBundle\Entity\ZoneTouristiqueUnifie'
        ));
    }

    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        parent::finishView($view, $form, $options); // TODO: Change the autogenerated stub
//        dump($view);die;
        foreach ($view->children['zoneTouristiques'] as $zoneTouristique) {
//            dump($zoneTouristique);
            if ($zoneTouristique->vars['value']->getSite()->getCrm() == 1) {
                $zoneTouristiqueCrm = $zoneTouristique;
            } else {
                foreach ($zoneTouristique->children['images'] as $key => $image) {
                    if ($image->vars['value']->getActif() == true) {

//                        dump($zoneTouristique->vars['value']->getSite()->getId());
                        $siteId = $zoneTouristique->vars['value']->getSite()->getId();
//                    $zoneTouristiqueCrm->children['images']->children[$key]
                        $zoneTouristiqueCrm->children['images']->children[$key]->children['sites']->children[$siteId]->vars['attr'] = array('checked' => 'checked');
//                        dump($zoneTouristiqueCrm->children['images']->children[$key]->children['sites']->children[$siteId]->vars['attr']);
                    }
                }
                foreach ($zoneTouristique->children['photos'] as $key => $photo) {
                    if ($photo->vars['value']->getActif() == true) {

                        $siteId = $zoneTouristique->vars['value']->getSite()->getId();
//                    $zoneTouristiqueCrm->children['photos']->children[$key]
                        $zoneTouristiqueCrm->children['photos']->children[$key]->children['sites']->children[$siteId]->vars['attr'] = array('checked' => 'checked');
                    }
                }
                foreach ($zoneTouristique->children['videos'] as $key => $video) {
                    if ($video->vars['value']->getActif() == true) {

                        $siteId = $zoneTouristique->vars['value']->getSite()->getId();
                        $zoneTouristiqueCrm->children['videos']->children[$key]->children['sites']->children[$siteId]->vars['attr'] = array('checked' => 'checked');
                    }
                }
            }

        }
//        die;
    }
    

}
