CREATE TABLE decote_traduction (id INT UNSIGNED AUTO_INCREMENT NOT NULL, decote_id INT UNSIGNED DEFAULT NULL, langue_id INT UNSIGNED DEFAULT NULL, titre VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, INDEX IDX_EEC8A9EA5DBDC32 (decote_id), INDEX IDX_EEC8A9E2AADBACD (langue_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE decote_traduction ADD CONSTRAINT FK_EEC8A9EA5DBDC32 FOREIGN KEY (decote_id) REFERENCES decote (id);
ALTER TABLE decote_traduction ADD CONSTRAINT FK_EEC8A9E2AADBACD FOREIGN KEY (langue_id) REFERENCES langue (id);

CREATE TABLE decote_logement (decote_id INT UNSIGNED NOT NULL, logement_id INT UNSIGNED NOT NULL, INDEX IDX_BF117C16A5DBDC32 (decote_id), INDEX IDX_BF117C1658ABF955 (logement_id), PRIMARY KEY(decote_id, logement_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE decote_logement ADD CONSTRAINT FK_BF117C16A5DBDC32 FOREIGN KEY (decote_id) REFERENCES decote (id);
ALTER TABLE decote_logement ADD CONSTRAINT FK_BF117C1658ABF955 FOREIGN KEY (logement_id) REFERENCES logement (id);