<?php

namespace Mondofute\Bundle\DescriptionForfaitSkiBundle\Repository;

/**
 * DescriptionForfaitSkiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescriptionForfaitSkiRepository extends \Doctrine\ORM\EntityRepository
{
}
