<?php

namespace Mondofute\Bundle\DescriptionForfaitSkiBundle\Repository;

/**
 * LigneDescriptionForfaitSkiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneDescriptionForfaitSkiRepository extends \Doctrine\ORM\EntityRepository
{
}
