<?php

namespace Mondofute\Bundle\MotClefBundle\Repository;

/**
 * MotClefTraductionHebergementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotClefTraductionHebergementRepository extends \Doctrine\ORM\EntityRepository
{
}
