<?php

namespace Mondofute\Bundle\MotClefBundle\Repository;

/**
 * MotClefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotClefRepository extends \Doctrine\ORM\EntityRepository
{
}
