<?php

namespace Mondofute\Bundle\MotClefBundle\Repository;

/**
 * MotClefTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotClefTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
