<?php

namespace Mondofute\Bundle\PromotionBundle\Repository;

/**
 * PromotionHebergementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionHebergementRepository extends \Doctrine\ORM\EntityRepository
{
}
