<?php

namespace Mondofute\Bundle\PromotionBundle\Repository;

/**
 * PromotionPeriodeSejourDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionPeriodeSejourDateRepository extends \Doctrine\ORM\EntityRepository
{
}
