<?php

namespace Mondofute\Bundle\CodePromoApplicationBundle\Repository;

/**
 * CodePromoLogementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodePromoLogementRepository extends \Doctrine\ORM\EntityRepository
{
}
