<?php

namespace Mondofute\Bundle\CodePromoApplicationBundle\Repository;

/**
 * CodePromoFournisseurPrestationAnnexeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodePromoFournisseurPrestationAnnexeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySite($fournisseurId, $siteId = 1)
    {
        $q = $this->getEntityManager()->createQueryBuilder();
        $q
            ->from('MondofuteCodePromoApplicationBundle:CodePromoFournisseurPrestationAnnexe',
                'codePromoFournisseurPrestationAnnexe')
            ->select('codePromoFournisseurPrestationAnnexe')
            ->join('codePromoFournisseurPrestationAnnexe.codePromo', 'codePromo')
            ->join('codePromo.site', 'site')
            ->join('codePromoFournisseurPrestationAnnexe.fournisseur', 'fournisseur')
            ->where('site.id = :siteId')
            ->setParameter('siteId', $siteId)
            ->andWhere('fournisseur.id = :fournisseurId')
            ->setParameter('fournisseurId', $fournisseurId);

        $result = $q->getQuery()->getResult();

        return $result;
    }
}
