<?php

namespace Mondofute\Bundle\CodePromoApplicationBundle\Repository;

/**
 * CodePromoLogementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodePromoLogementRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteByLogement($logementId)
    {
        $sql = 'DELETE FROM code_promo_logement WHERE logement_id = :logementId';
        $params = array(
            'logementId' => $logementId,
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params);
    }
}
