<?php

namespace Mondofute\Bundle\CodePromoAppolBundle\Bundle\Repository;

/**
 * CodePromoApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodePromoFournisseurRepository extends \Doctrine\ORM\EntityRepository
{
}
