<?php

namespace Mondofute\Bundle\CodePromoApplicationBundle\Repository;

/**
 * CodePromoFamillePrestationAnnexeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodePromoFamillePrestationAnnexeRepository extends \Doctrine\ORM\EntityRepository
{
}
