/*CREATE TABLE remise_code_promo (id INT UNSIGNED NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE remise_decote (id INT UNSIGNED NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE remise_promotion (id INT UNSIGNED NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

ALTER TABLE remise_code_promo ADD CONSTRAINT FK_4581716FBF396750 FOREIGN KEY (id) REFERENCES commande_ligne (id) ON DELETE CASCADE;
ALTER TABLE remise_decote ADD CONSTRAINT FK_8903E0E5BF396750 FOREIGN KEY (id) REFERENCES commande_ligne (id) ON DELETE CASCADE;
ALTER TABLE remise_promotion ADD CONSTRAINT FK_6AD9D447BF396750 FOREIGN KEY (id) REFERENCES commande_ligne (id) ON DELETE CASCADE;

ALTER TABLE remise_code_promo ADD code_promo_id INT UNSIGNED DEFAULT NULL;
ALTER TABLE remise_code_promo ADD CONSTRAINT FK_4581716F294102D4 FOREIGN KEY (code_promo_id) REFERENCES code_promo (id);
CREATE INDEX IDX_4581716F294102D4 ON remise_code_promo (code_promo_id);
ALTER TABLE remise_decote ADD decote_id INT UNSIGNED DEFAULT NULL;
ALTER TABLE remise_decote ADD CONSTRAINT FK_8903E0E5A5DBDC32 FOREIGN KEY (decote_id) REFERENCES decote (id);
CREATE INDEX IDX_8903E0E5A5DBDC32 ON remise_decote (decote_id);
ALTER TABLE remise_promotion ADD promotion_id INT UNSIGNED DEFAULT NULL;
ALTER TABLE remise_promotion ADD CONSTRAINT FK_6AD9D447139DF194 FOREIGN KEY (promotion_id) REFERENCES promotion (id);
CREATE INDEX IDX_6AD9D447139DF194 ON remise_promotion (promotion_id);*/

ALTER TABLE commande_ligne ADD date_paiement DATETIME DEFAULT NULL;