/*CREATE TABLE participant (id INT UNSIGNED AUTO_INCREMENT NOT NULL, civilite_id INT UNSIGNED DEFAULT NULL, commande_ligne_id INT UNSIGNED DEFAULT NULL, date_creation DATETIME DEFAULT NULL, date_modification DATETIME DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, INDEX IDX_D79F6B1139194ABF (civilite_id), INDEX IDX_D79F6B118C6396EC (commande_ligne_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE physique_moyenscomm (physique_id INT UNSIGNED NOT NULL, moyenComm_id INT UNSIGNED NOT NULL, INDEX IDX_D626BE1453D0E798 (physique_id), INDEX IDX_D626BE146A62432C (moyenComm_id), PRIMARY KEY(physique_id, moyenComm_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE physique_nationalite (physique_id INT UNSIGNED NOT NULL, nationalite_id INT UNSIGNED NOT NULL, INDEX IDX_395ECB8853D0E798 (physique_id), INDEX IDX_395ECB881B063272 (nationalite_id), PRIMARY KEY(physique_id, nationalite_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE participant ADD CONSTRAINT FK_D79F6B1139194ABF FOREIGN KEY (civilite_id) REFERENCES civilite (id);
ALTER TABLE participant ADD CONSTRAINT FK_D79F6B118C6396EC FOREIGN KEY (commande_ligne_id) REFERENCES commande_ligne (id);
ALTER TABLE physique_moyenscomm ADD CONSTRAINT FK_D626BE1453D0E798 FOREIGN KEY (physique_id) REFERENCES participant (id);
ALTER TABLE physique_moyenscomm ADD CONSTRAINT FK_D626BE146A62432C FOREIGN KEY (moyenComm_id) REFERENCES moyen_communication (id) ON DELETE CASCADE;
ALTER TABLE physique_nationalite ADD CONSTRAINT FK_395ECB8853D0E798 FOREIGN KEY (physique_id) REFERENCES participant (id);
ALTER TABLE physique_nationalite ADD CONSTRAINT FK_395ECB881B063272 FOREIGN KEY (nationalite_id) REFERENCES nationalite (id);*/

ALTER TABLE participant ADD date_naissance DATE DEFAULT NULL;
