<?php

namespace Mondofute\Bundle\CommandeBundle\Repository;

/**
 * CommandeStatutDossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeStatutDossierRepository extends \Doctrine\ORM\EntityRepository
{
}
