<?php

namespace Mondofute\Bundle\CommandeBundle\Repository;

/**
 * CommandeLigneSejourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeLigneSejourRepository extends \Doctrine\ORM\EntityRepository
{
}
