<?php

namespace Mondofute\Bundle\CommandeBundle\Repository;

/**
 * GroupeStatutDossierTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeStatutDossierTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
