<?php

namespace Mondofute\Bundle\CommandeBundle\Repository;

/**
 * StatutDossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutDossierRepository extends \Doctrine\ORM\EntityRepository
{
}
