<?php

namespace Mondofute\Bundle\UtilisateurBundle\Repository;

/**
 * UtilisateurUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurUserRepository extends \Doctrine\ORM\EntityRepository
{
}
