<?php

namespace Mondofute\Bundle\DomaineBundle\Repository;

/**
 * DomaineCarteIdentiteImageTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomaineCarteIdentiteImageTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
