<?php

namespace Mondofute\Bundle\DomaineBundle\Repository;

/**
 * TypePisteTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePisteTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
