<?php

namespace Mondofute\Bundle\DomaineBundle\Repository;

/**
 * TypePisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePisteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $locale
     * @return \Doctrine\ORM\QueryBuilder
     */
    // récupérer les traductioin des niveau skieur crm qui sont de la langue locale
    public function getTraductionsByLocale($locale)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('tp , tpt ')
            ->from('MondofuteDomaineBundle:TypePiste', 'tp')
            ->join('tp.traductions', 'tpt')
            ->join('tpt.langue', 'l')
            ->where("l.code = '$locale'");
        $qb->orderBy('tp.id', 'ASC');

        return $qb;
    }
}
