CREATE TABLE region_video (id INT UNSIGNED AUTO_INCREMENT NOT NULL, region_id INT UNSIGNED DEFAULT NULL, video_id INT DEFAULT NULL, actif TINYINT(1) DEFAULT '0' NOT NULL, INDEX IDX_C4A3D93498260155 (region_id), INDEX IDX_C4A3D93429C1004E (video_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE region_video_traduction (id INT UNSIGNED AUTO_INCREMENT NOT NULL, video_id INT UNSIGNED DEFAULT NULL, langue_id INT UNSIGNED DEFAULT NULL, libelle VARCHAR(255) NOT NULL, INDEX IDX_B4B5982929C1004E (video_id), INDEX IDX_B4B598292AADBACD (langue_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE region_video ADD CONSTRAINT FK_C4A3D93498260155 FOREIGN KEY (region_id) REFERENCES region (id);
ALTER TABLE region_video ADD CONSTRAINT FK_C4A3D93429C1004E FOREIGN KEY (video_id) REFERENCES media__media (id);
ALTER TABLE region_video_traduction ADD CONSTRAINT FK_B4B5982929C1004E FOREIGN KEY (video_id) REFERENCES region_video (id);
ALTER TABLE region_video_traduction ADD CONSTRAINT FK_B4B598292AADBACD FOREIGN KEY (langue_id) REFERENCES langue (id);
