<?php

namespace Mondofute\Bundle\ChoixBundle\Repository;

/**
 * OuiNonNCTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OuiNonNCTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
