<?php

namespace Mondofute\Bundle\ChoixBundle\Repository;

/**
 * OuiNonNCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OuiNonNCRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $locale
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getTraductionsByLocale($locale)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('ouiNonNc , traductions ')
            ->from('MondofuteChoixBundle:OuiNonNC', 'ouiNonNc')
            ->join('ouiNonNc.traductions', 'traductions')
            ->join('traductions.langue', 'l')
            ->where("l.code = '$locale'");
        $qb->orderBy('ouiNonNc.classement', 'ASC');

        return $qb;
    }
}
