<?php

namespace Mondofute\Bundle\HebergementBundle\Repository;

/**
 * EmplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmplacementRepository extends \Doctrine\ORM\EntityRepository
{
}
