<?php

namespace Mondofute\Bundle\HebergementBundle\Repository;

/**
 * HebergementVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HebergementVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
