<?php

namespace Mondofute\Bundle\HebergementBundle\Repository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * HebergementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HebergementRepository extends \Doctrine\ORM\EntityRepository
{
}
