<?php

namespace Mondofute\Bundle\HebergementBundle\Repository;

/**
 * HebergementTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HebergementTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
