<?php

namespace Mondofute\Bundle\HebergementBundle\Repository;

/**
 * TypeHebergementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeHebergementRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $locale
     * @return \Doctrine\ORM\QueryBuilder
     */
    // récupérer les traduction des stations crm qui sont de la langue locale
    public function getTraductionsByLocale($locale)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('th , tht')
            ->from('MondofuteHebergementBundle:TypeHebergement', 'th')
            ->join('th.traductions', 'tht')
            ->join('th.site', 'site')
            ->join('tht.langue', 'l')
            ->where("l.code = '$locale'");
//        ->setParameter('code' , $locale)
        $qb->orderBy('th.id', 'ASC');

        return $qb;
    }
}
