<?php

namespace Mondofute\Bundle\HebergementBundle\Repository;

/**
 * TypeHebergementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeHebergementRepository extends \Doctrine\ORM\EntityRepository
{
}
