<?php

namespace Mondofute\Bundle\HebergementBundle\Repository;

/**
 * UniteClassementHebergementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniteClassementHebergementRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $locale
     * @return \Doctrine\ORM\QueryBuilder
     */
    // récupérer les traduction des stations crm qui sont de la langue locale
    public function getTraductionsByLocale($locale)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('uch , ucht')
            ->from('MondofuteHebergementBundle:UniteClassementHebergement', 'uch')
            ->join('uch.traductions', 'ucht')
            ->join('ucht.langue', 'l')
            ->where("l.code = '$locale'");
//        ->setParameter('code' , $locale)
        $qb->orderBy('uch.id', 'ASC');

        return $qb;
    }
}
