<?php

namespace Mondofute\Bundle\HebergementBundle\Repository;

/**
 * UniteClassementHebergementTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniteClassementHebergementTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
