<?php

namespace Mondofute\Bundle\CoupDeCoeurBundle\Repository;

/**
 * CoupDeCoeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoupDeCoeurRepository extends \Doctrine\ORM\EntityRepository
{
}
